### ISSUE TITLE
`TypeError` when running `simulate.py` with `export USE_CUPY=1`

### ISSUE THREAD

**Issue by fredericpoitevin** [apeck12/cmtip#25]
The following simulation script - which does not use the GPU - works on S3DF:
```bash
#!/bin/bash

#SBATCH --job-name=cmtip-sim
#SBATCH --output=cmtip-sim.out
#SBATCH --error=cmtip-sim.err
#SBATCH --time=0:15:00
#SBATCH --account lcls
#SBATCH --partition=ampere
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus a100:1
#SBATCH --cpus-per-task=16

source /sdf/group/lcls/ds/ana/sw/conda1/manage/bin/psconda.sh
conda activate /sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda

# USE_CUPY needs to be set for Skopi to use GPUs
#export USE_CUPY=1
# Here we test with CPUs only
export USE_CUPY=0

work_dir=${PWD}
mkdir -p simulation
code_dir=$(python -c "import site; print(''.join(site.getsitepackages()))")
cd ${work_dir}/simulation

python ${code_dir}/cmtip/simulate.py -b ${work_dir}/amo86615/amo86615.beam -p ${work_dir}/2cex_a.pdb -d pnccd ${work_dir}/amo86615/PNCCD::CalibV1/Camp.0:pnCCD.1/geometry/0-end.data 0.04 -n 100 -o 2cexa_sim.h5 -q -s 100
```

However, when setting `USE_CUPY` to 1 instead of 0, it fails with the following error:
```bash
Traceback (most recent call last):
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/simulate.py", line 179, in <module>
    main()
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/simulate.py", line 174, in main
    simulate_writeh5(args)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/simulate.py", line 89, in simulate_writeh5
    f.create_dataset("pixel_position_reciprocal", data=np.moveaxis(exp.det.pixel_position_reciprocal, -1, 0)) # s-vectors in m-1
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/h5py/_hl/group.py", line 161, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 48, in make_new_dset
    data = base.array_for_new_object(data, specified_dtype=dtype)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/h5py/_hl/base.py", line 118, in array_for_new_object
    data = np.asarray(data, order="C", dtype=as_dtype)
  File "cupy/_core/core.pyx", line 1480, in cupy._core.core._ndarray_base.__array__
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```

I'll try to fix by checking things like this:
```python
if isinstance(totos, np.ndarray):
  totos = np.array(totos)
else:
  totos = np.array([toto.get() for toto in totos])
```

**Comment by JayShenoy** [comment]
Made a PR to fix this issue: [Pull Request 27](https://github.com/apeck12/cmtip/pull/27)

**Comment by fredericpoitevin** [comment]
@JayShenoy I leave this issue open, not sure #27 fixed this particular issue?
