### ISSUE TITLE
`RuntimeError` when running `reconstruct.py`

### ISSUE THREAD

**Issue by fredericpoitevin** [apeck12/cmtip#26]
The following script, where the `cmtip-cuda` environment contains this fork's version of `cmtip`, runs on S3DF:
```bash
#!/bin/bash

source /sdf/group/lcls/ds/ana/sw/conda1/manage/bin/psconda.sh
conda activate /sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda

work_dir=${PWD}
mkdir -p reconstruction_squaredet

code_dir=$(python -c "import site; print(''.join(site.getsitepackages()))")


for vnum in `seq 0 9`
do

cat >> temp_${vnum}.sh <<EOF
#!/bin/bash

#SBATCH --job-name=cmtip-rec_${vnum}
#SBATCH --output=cmtip-rec_${vnum}.out
#SBATCH --error=cmtip-rec_${vnum}.err

#SBATCH --time=15:00:00
#SBATCH --account lcls
#SBATCH -p milano
#SBATCH --ntasks=8
#SBATCH --mem=196G

module load mpi/mpich-x86_64

source /sdf/group/lcls/ds/ana/sw/conda1/manage/bin/psconda.sh

conda activate /sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda

cd ${work_dir}/reconstruction_squaredet

#/sdf/home/f/fpoitevi/sw/cmtip/cmtip
#python ${code_dir}/cmtip/reconstruct.py -i ${work_dir}/simulation_squaredet/2cexa_sim_64_dist_01_5k_scaled.h5 -t 5000 -b 2 -m 64 -n 10 -o rec_${vnum} 
python /sdf/home/f/fpoitevi/sw/cmtip/cmtip/reconstruct.py -i ${work_dir}/simulation_squaredet/2cexa_sim_64_dist_01_5k_scaled.h5 -t 5000 -b 2 -m 64 -n 10 -o rec_${vnum} 

EOF

sbatch temp_${vnum}.sh
done
```

yields the following error:
```bash
Traceback (most recent call last):
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/reconstruct.py", line 128, in <module>
    main()
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/reconstruct.py", line 123, in main
    run_mtip(data, args['M'], args['output'], aligned=args['aligned'], 
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/reconstruct.py", line 52, in run_mtip
    ac = autocorrelation.solve_ac(checkpoint['generation'],
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/autocorrelation/autocorrelation.py", line 234, in solve_ac
    W, d = setup_linops(H, K, L, data,
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/autocorrelation/autocorrelation.py", line 146, in setup_linops
    ugrid_conv = nufft.adjoint_cpu(np.ones_like(data), H_, K_, L_, 
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/cmtip/nufft/adjoint.py", line 33, in adjoint_cpu
    nfft.nufft3d1(H_, K_, L_, nuvect, out=ugrid, eps=1.0e-15, isign=1)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/finufft/_interfaces.py", line 864, in nufft3d1
    return invoke_guru(3,1,x,y,z,c,None,None,None,out,isign,eps,n_modes,**kwargs)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/finufft/_interfaces.py", line 597, in invoke_guru
    out = plan.execute(c,f)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/finufft/_interfaces.py", line 238, in execute
    _data = _cchkf(data)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip-cuda/lib/python3.9/site-packages/finufft/_interfaces.py", line 362, in _cchkf
    raise RuntimeError('FINUFFT data type must be complex64 for single precision, data may have mixed precision types')
RuntimeError: FINUFFT data type must be complex64 for single precision, data may have mixed precision types
```

**Comment by fredericpoitevin** [comment]
@JayShenoy [fork](https://github.com/JayShenoy/cmtip) resolves the issue: consider making a PR?

**Comment by JayShenoy** [comment]
Made a PR to fix this issue: [Pull Request 27](https://github.com/apeck12/cmtip/pull/27)
