### ISSUE TITLE
`ValueError`: negative dimensions not allowed

### ISSUE THREAD

**Issue by fredericpoitevin** [apeck12/cmtip#29]
On S3DF at this path `/sdf/group/lcls/ds/tools/tpprwr/test/cmtip`, in a `cmtip` environment built using [this script](https://github.com/lcls-users/tpprwr/blob/cmtip/conda/install-s3df-cuda-cmtip.slurm), I did:

1. Simulate a pnccd dataset using `sbatch cmtip_simulation_s3df.sh`:
```bash
Simulating diffraction images
Simulated dataset saved to 2cexa_sim2.h5
elapsed time is 0.39
```
2. Attempt to reconstruct using `./cmtip_reconstruction_s3df.sh`:
This failed with
```bash
Traceback (most recent call last):
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip/lib/python3.9/site-packages/cmtip/reconstruct_mpi.py", line 177, in <module>
    main()
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip/lib/python3.9/site-packages/cmtip/reconstruct_mpi.py", line 160, in main
    data = load_h5(args['input'], start=rank*n_images_batch, end=(rank+1)*n_images_batch)
  File "/sdf/group/lcls/ds/tools/conda_envs/cmtip/lib/python3.9/site-packages/cmtip/prep_data.py", line 54, in load_h5
    data['intensities'] = np.zeros((attrs['n_images'],) + attrs['det_shape']).astype(np.float32)
ValueError: negative dimensions are not allowed
(edited)
```

**Comment by fredericpoitevin** [comment]
Turned out the error was that I was asking to reconstruct from 10,000 images while the simulated dataset only had 100:
```bash
(/sdf/group/lcls/ds/tools/conda_envs/cmtip) [fpoitevi@sdfiana002 cmtip]$ more cmtip-rec_0.out 
rank: 1 | n_images_batch: 1250
Loading data from /sdf/group/lcls/ds/tools/tpprwr/test/cmtip/simulation/2cexa_sim2.h5
attrs['n_images'] = -1150
```
